version: '3'

services:
  provider-app:
    container_name: provider-app
    build:
      context: src/vendor/laravel/sail/runtimes/8.3
      dockerfile: src/vendor/laravel/sail/runtimes/8.3/Dockerfile
      args:
        WWWGROUP: 1000
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8086:80'
      - '5173:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-debug}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - .:/var/www/html
    networks:
      - sail
    depends_on:
      - provider-database
      - provider-mailpit
      - provider-redis

  provider-database:
    container_name: provider-database
    image: 'mysql/mysql-server:8.0'
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './docker/db:/var/lib/mysql'
    networks:
      - sail

  provider-mailpit:
    container_name: provider-mailpit
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail

  provider-redis:
    container_name: provider-redis
    image: 'redis:alpine'
    ports:
      - 6379:6379
    networks:
      - sail

networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
